{
 "title": "Objectstore performance stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "oss",
    "label": "objectstore",
    "query": {
     "query": "nutanix_objectstore_total_heads"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "up" } }
  ]
 },
 "panels": [
  {
   "title": "Total requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_total_requests_sec{objectstore=~\"$oss\",job=~\"$job\"}",
     "legendFormat": "{{ objectstore }}"
    }
   ]
  },
  {
   "title": "GETS/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_gets_sec{objectstore=~\"$oss\", job=~\"$job\"}",
     "legendFormat": "{{ bucket }}({{ objectstore }})"
    }
   ]
  },
  { "title": "Performance monitors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Throughput out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_total_throughput_out_sec{objectstore=~\"$oss\",job=~\"$job\"}",
     "legendFormat": "{{ bucket }}({{ objectstore }})"
    }
   ]
  },
  {
   "title": "PUTS/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_puts_sec{objectstore=~\"$oss\", job=~\"$job\"}",
     "legendFormat": "{{ bucket }}({{ objectstore }})"
    }
   ]
  },
  {
   "title": "Throughput in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_total_throughput_in_sec{objectstore=~\"$oss\",job=~\"$job\"}",
     "legendFormat": "{{ bucket }}({{ objectstore }})"
    }
   ]
  },
  {
   "title": "Number of multipart uploads/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_total_multipart_uploads{objectstore=~\"$oss\",job=~\"$job\"}",
     "legendFormat": "{{ bucket }}({{ objectstore }})"
    }
   ]
  },
  {
   "title": "object LISTS/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_total_lists{objectstore=~\"$oss\",job=~\"$job\"}",
     "legendFormat": "{{ bucket }}({{ objectstore }})"
    }
   ]
  },
  {
   "title": "Total number of multipart lists/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_total_multipart_lists{objectstore=~\"$oss\",job=~\"$job\"}",
     "legendFormat": "{{ bucket }}({{ objectstore }})"
    }
   ]
  },
  {
   "title": "POSTS/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_total_posts{objectstore=~\"$oss\",job=~\"$job\"}",
     "legendFormat": "{{ bucket }}({{ objectstore }})"
    }
   ]
  },
  {
   "title": "DELETE/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_total_deletes{objectstore=~\"$oss\",job=~\"$job\"}",
     "legendFormat": "{{ bucket }}({{ objectstore }})"
    }
   ]
  },
  {
   "title": "HEAD/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_total_heads{objectstore=~\"$oss\",job=~\"$job\"}",
     "legendFormat": "{{ bucket }}({{ objectstore }})"
    }
   ]
  },
  {
   "title": "S3 Select queries/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_total_select_content_ops{objectstore=~\"$oss\",job=~\"$job\"}",
     "legendFormat": "{{ bucket }}({{ objectstore }})"
    }
   ]
  }
 ]
}