{
 "title": "Objectstore stats",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "oss",
    "label": "objectstore",
    "query": {
     "query": "nutanix_objectstore_total_heads"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "up" } }
  ]
 },
 "panels": [
  {
   "title": "oss level dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total number of buckets",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "nutanix_objectstore_num_buckets{objectstore=~\"$oss\", job=~\"$job\"}",
     "legendFormat": "{{ objectstore }}"
    }
   ]
  },
  {
   "title": "Total number of objects ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "nutanix_objectstore_num_objects{objectstore=~\"$oss\", job=~\"$job\"}",
     "legendFormat": "{{ objectstore }}"
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "nutanix_objectstore_usage_bytes{objectstore=~\"$oss\", job=~\"$job\"}/1073741824",
     "legendFormat": "{{ objectstore }}"
    }
   ]
  }
 ]
}