{
 "title": "Objectstore resource stats monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "oss",
    "label": "oss",
    "query": {
     "query": "nutanix_objectstore_total_heads"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "nutanix_objectstore_container_cpu_usage_seconds_total"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "up" } }
  ]
 },
 "panels": [
  {
   "title": "Resource Monitors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod instance 0 - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (nutanix_objectstore_container_cpu_usage_seconds_total{container_name=~\"$container\",pod_name=~\"$container-0\", objectstore=~\"$oss\", job=~\"$job\"}[5m])) / 9.23 *1000",
     "legendFormat": "{{ objectstore}}_{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Pod instance 0 - Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nutanix_objectstore_container_memory_usage_bytes{container_name=~\"$container\",pod=~\"$container-1\", objectstore=~\"$oss\", job=~\"$job\"}",
     "legendFormat": "{{ objectstore }}_{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Pod instance 1 - CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (nutanix_objectstore_container_cpu_usage_seconds_total{container_name=~\"$container\",pod=~\"$container-1\", objectstore=~\"$oss\", job=~\"$job\"}[5m])) / 13.84 *1000",
     "legendFormat": "{{ objectstore }}_{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Pod instance 1 - Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nutanix_objectstore_container_memory_usage_bytes{container_name=~\"$container\",pod_name=~\"$container-1\", objectstore=~\"$oss\", job=~\"$job\"}",
     "legendFormat": "{{ objectstore }}_{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Pod instance 2 - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (nutanix_objectstore_container_cpu_usage_seconds_total{container_name=~\"$container\", pod=~\"$container-2\", objectstore=~\"$oss\", job=~\"$job\"}[5m])) / 23.18 *1000",
     "legendFormat": "{{ objectstore }}_{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Pod instance 2 - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nutanix_objectstore_container_memory_usage_bytes{container_name=~\"$container\",pod_name=~\"$container-2\", objectstore=~\"$oss\", job=~\"$job\"}",
     "legendFormat": "{{ objectstore }}_{{ instance_id }}"
    }
   ]
  }
 ]
}